#############################################################################
# Makefile for building: Remove\ MC\ Headers.app/Contents/MacOS/Remove\ MC\ Headers
# Generated by qmake (3.1) (Qt 5.15.1)
# Project:  rmch.pro
# Template: app
# Command: /usr/local/opt/qt/bin/qmake -o Makefile rmch.pro -config release
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/qt/5.15.1/lib/QtQuickControls2.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtQuick.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtQmlModels.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtQml.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.15.1/lib
QMAKE         = /usr/local/opt/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/opt/qt/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/opt/qt/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Remove\ MC\ Headers1.0.0
DISTDIR = /Users/marcelo/CLionProjects/RemoveMCHeaders/.tmp/Remove\ MC\ Headers1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.15.1/lib -framework QtQuickControls2 -framework QtQuick -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtQmlModels -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		interface/rmch_interface.cpp moc_rmch_interface.cpp
OBJECTS       = main.o \
		rmch_interface.o \
		moc_rmch_interface.o
DIST          = /usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/lex.prf \
		rmch.pro interface/rmch_interface.hpp \
		qt/main_window.hpp main.cpp \
		interface/rmch_interface.cpp
QMAKE_TARGET  = Remove\ MC\ Headers
DESTDIR       = 
TARGET        = Remove\ MC\ Headers.app/Contents/MacOS/Remove\ MC\ Headers

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14.6
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/marcelo/CLionProjects/RemoveMCHeaders/rmch.pro


include /usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Remove\ MC\ Headers.app/Contents/MacOS/Remove\ MC\ Headers:  $(OBJECTS)  
	@test -d Remove\ MC\ Headers.app/Contents/MacOS/ || mkdir -p Remove\ MC\ Headers.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: rmch.pro /usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/lex.prf \
		rmch.pro \
		/usr/local/Cellar/qt/5.15.1/lib/QtQuickControls2.framework/Resources/QtQuickControls2.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtQuick.framework/Resources/QtQuick.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtQmlModels.framework/Resources/QtQmlModels.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtQml.framework/Resources/QtQml.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile rmch.pro -config release
/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources_functions.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/lex.prf:
rmch.pro:
/usr/local/Cellar/qt/5.15.1/lib/QtQuickControls2.framework/Resources/QtQuickControls2.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtQuick.framework/Resources/QtQuick.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtQmlModels.framework/Resources/QtQmlModels.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtQml.framework/Resources/QtQml.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtNetwork.framework/Resources/QtNetwork.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile rmch.pro -config release

qmake_all: FORCE

Remove\ MC\ Headers.app/Contents/PkgInfo: 
	@test -d Remove\ MC\ Headers.app/Contents || mkdir -p Remove\ MC\ Headers.app/Contents
	@$(DEL_FILE) Remove\ MC\ Headers.app/Contents/PkgInfo
	@echo "APPL????" > Remove\ MC\ Headers.app/Contents/PkgInfo
Remove\ MC\ Headers.app/Contents/Resources/empty.lproj: 
	@test -d Remove\ MC\ Headers.app/Contents/Resources || mkdir -p Remove\ MC\ Headers.app/Contents/Resources
	@touch Remove\ MC\ Headers.app/Contents/Resources/empty.lproj
	
Remove\ MC\ Headers.app/Contents/Info.plist: 
	@test -d Remove\ MC\ Headers.app/Contents || mkdir -p Remove\ MC\ Headers.app/Contents
	@$(DEL_FILE) Remove\ MC\ Headers.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Remove-MC-Headers,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.Remove-MC-Headers,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Remove MC Headers,g" -e "s,@LIBRARY@,Remove MC Headers,g" -e "s,\$${EXECUTABLE_NAME},Remove MC Headers,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/Info.plist.app >Remove\ MC\ Headers.app/Contents/Info.plist

all: Makefile \
		Remove\ MC\ Headers.app/Contents/PkgInfo \
		Remove\ MC\ Headers.app/Contents/Resources/empty.lproj \
		Remove\ MC\ Headers.app/Contents/Info.plist Remove\ MC\ Headers.app/Contents/MacOS/Remove\ MC\ Headers

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.15.1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents interface/rmch_interface.hpp qt/main_window.hpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp interface/rmch_interface.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Remove\ MC\ Headers.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -config release

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.15.1/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.15.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_rmch_interface.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_rmch_interface.cpp
moc_rmch_interface.cpp: interface/rmch_interface.hpp \
		qt/main_window.hpp \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.15.1/bin/moc
	/usr/local/Cellar/qt/5.15.1/bin/moc $(DEFINES) --include /Users/marcelo/CLionProjects/RemoveMCHeaders/moc_predefs.h -I/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang -I/Users/marcelo/CLionProjects/RemoveMCHeaders -I/usr/local/Cellar/qt/5.15.1/lib/QtQuickControls2.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtQuick.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtQmlModels.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtQml.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.15.1/lib interface/rmch_interface.hpp -o moc_rmch_interface.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /usr/local/Cellar/qt/5.15.1/lib/QtQuickControls2.framework/Headers/QQuickStyle \
		/usr/local/Cellar/qt/5.15.1/lib/QtQuickControls2.framework/Headers/qquickstyle.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QStyleFactory \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qstylefactory.h \
		interface/rmch_interface.hpp \
		qt/main_window.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

rmch_interface.o: interface/rmch_interface.cpp /usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QFileDialog \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qfiledialog.h \
		interface/rmch_interface.hpp \
		qt/main_window.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rmch_interface.o interface/rmch_interface.cpp

moc_rmch_interface.o: moc_rmch_interface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rmch_interface.o moc_rmch_interface.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

